### ISSUE TITLE
ghê chưa

### ISSUE THREAD

**Issue by lebathang** [KietCSE/torrent-app#7]
m làm app down torrent à hay là quản lí file torrent ấy, s ko thấy hướng dẫn cài ấy để test xem sao

**Comment by KietCSE** [comment]
cái này là bt ở trường thôi, code lại một mạng torrent đơn giản, cái này là code app bên phía người dùng, t chưa viết hướng dẫn sử dụng. Còn có code cho server nữa, mà t tắt cái server trên aws rồi nên h không xài được đâu :((

**Comment by lebathang** [comment]
à cái này là code bên phía torrent client đúng ko, còn cái code server là cái tracker torrent gì đó đúng ko 😄

**Comment by KietCSE** [comment]
đúng rồi á
